language: cpp
dist: trusty
sudo: required
services:
  - docker

matrix:
  include:
  - os: linux
    compiler: gcc

before_install:
  - git fetch --tags && git fetch

install:
  - ./scripts/$TRAVIS_OS_NAME/install.sh

script:
  - ./scripts/$TRAVIS_OS_NAME/script.sh

after_success:
  - ./scripts/$TRAVIS_OS_NAME/after_success.sh

notifications:
  email:
    on_success: never
    on_failure: always
